create table student ( roll char(4),name char(10),email varchar(15),phone number(10),dept char(7),marks NUMBER(4));
desc student;
INSERT into student VALUES('1','Farhad','farhad@2022',7845963214,'MCA',86);
INSERT into student VALUES('2','Sakil','sa@gmail.com',78459644,'MCA',89);
INSERT into student VALUES('3','Dipu','diu@hot.com',974563214,'BSc',75);
INSERT into student VALUES('4','Monoj','mnj@com',8745963214,'MCA',67);
INSERT into student VALUES('5','Imran','im@gmail.com',7845963214,'MTech',80);
INSERT into student VALUES('6','Asif','as@hotmail.com',7845963214,'BTech',50);
INSERT into student VALUES('7','Akash','ask@yahoo.com',6245963214,'BCA',86);
INSERT into student VALUES('8','Sarwar','sarwar@out.com',7845963214,'BCA',49);
select * from student;
select name,roll from student where dept='MCA';
commit;
select * from student;
select email,phone from student where name='Sakil' and dept='MCA';
select * from student where marks <=50;
delete DISTINCT * from student where name='Sarwar';
select * from student;
delete from student where name='Farhad';
select * from student;
select * from student order by roll;
commit;
update student set marks=95 where roll='8';
select name from student where marks in (80,95);
select count(marks) from student;
select TOP 3 * from student;
select * from student order by rand();